pipeline:

  build_wordpress:
    image: plugins/docker:1.12
    username:
      from_secret: docker_user
    password:
      from_secret: docker_pass
    repo: leejelley/wordpress
    tags: 
       - latest
    dockerfile: wordpress/Dockerfile

  build_nginx:
    image: plugins/docker:1.12
    username:
      from_secret: docker_user
    password:
      from_secret: docker_pass
    repo: leejelley/ngix
    tags:
       - latest
    dockerfile: nginx/Dockerfile
