#
pipeline:

  build_wordpress:
    secrets: [ docker_username, docker_password ]
    image: plugins/docker
    repo: leejelley/mbh_wordpress
    auto_tag: true
    auto_tag_suffix: latest
    dockerfile: wordpress/Dockerfile

  build_nginx:
    secrets: [ docker_username, docker_password ]
    image: plugins/docker
    repo: leejelley/mbh_nginx
    auto_tag: true
    auto_tag_suffix: latest
    dockerfile: nginx/Dockerfile
